// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Modal_popup.Models;
using System;
using System.Collections.Generic;

namespace Modal_popup.Models.Configurations
{
    public partial class EmployeeTbConfiguration : IEntityTypeConfiguration<EmployeeTb>
    {
        public void Configure(EntityTypeBuilder<EmployeeTb> entity)
        {
            entity.HasKey(e => e.EmpId)
                .HasName("PK__Employee__263E2DD35B79C4A0");

            entity.Property(e => e.EmpId).HasColumnName("Emp_id");

            entity.Property(e => e.EmpAge)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("Emp_age");

            entity.Property(e => e.EmpDepartment)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("Emp_department");

            entity.Property(e => e.EmpDesignation)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("Emp_designation");

            entity.Property(e => e.EmpGender)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("Emp_gender");

            entity.Property(e => e.EmpName)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("Emp_name");

            entity.Property(e => e.EmpPno)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("Emp_pno");

            entity.Property(e => e.EmpSalary)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("Emp_salary");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmployeeTb> entity);
    }
}
