// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Modal_popup.Models.Configurations;
using System;
using System.Collections.Generic;
#nullable disable

namespace Modal_popup.Models
{
    public partial class Employee_management_SystemContext : DbContext
    {
        public Employee_management_SystemContext()
        {
        }

        public Employee_management_SystemContext(DbContextOptions<Employee_management_SystemContext> options)
            : base(options)
        {
        }

        public virtual DbSet<EmployeeTb> EmployeeTb { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=BMINP5721-2304;Initial Catalog=Employee_management_System;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.EmployeeTbConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
