// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Modal_popup.Models
{
    public partial class EmployeeTb
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpAge { get; set; }
        public string EmpGender { get; set; }
        public string EmpDepartment { get; set; }
        public string EmpDesignation { get; set; }
        public string EmpPno { get; set; }
        public string EmpSalary { get; set; }
    }
}